apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vietaws
  region: ap-southeast-1
  version: "1.36"

vpc:
  availabilityZones: ["ap-southeast-1b", "ap-southeast-1c"]
  localZones: ["ap-southeast-1-han-1a"]
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
  # Standard node group in the primary region
  # - name: primary-nodes
  #   instanceType: t3.micro
  #   desiredCapacity: 1
  #   availabilityZones: ["ap-southeast-1b", "ap-southeast-1c"]

  # Specialized node group placed strictly inside the Local Zone
  - name: local-zone-nodes
    instanceType: c7i.large
    desiredCapacity: 1
    localZones: ["ap-southeast-1-han-1a"]
    # Best Practice: Add a taint to prevent general pods from scheduling here
    taints:
      - key: "local-zone"
        value: "true"
        effect: "NoSchedule"
